POST http://{{nbi_url}}/nbi/opr/add
Content-Type: application/json
authorization: Bearer {{nbi_token}}

{
  "id": "5f9ec620-bad9-51d7-a062-e6ac-00f0fa61",
  "email": "test@teamsacs.com",
  "username": "opr",
  "level": "opr",
  "remark": "opr"
}

###

POST http://{{nbi_url}}/nbi/opr/update
Content-Type: application/json
authorization: Bearer {{nbi_token}}

{
  "email": "test2@teamsacs.com",
  "username": "opr"
}

###

GET http://{{nbi_url}}/nbi/opr/query?equal[username]=opr
authorization: Bearer {{nbi_token}}

{}

###


GET http://{{nbi_url}}/nbi/opr/query
authorization: Bearer {{nbi_token}}

###


GET http://{{nbi_url}}/nbi/opr/delete?equal[username]=opr
authorization: Bearer {{nbi_token}}

###
