version: '2'
services:
  pgdb:
    image: timescale/timescaledb:latest-pg13
    container_name: "pgdb"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: teamsacs
      POSTGRES_USER: teamsacs
      POSTGRES_PASSWORD: teamsacs
    volumes:
      - "/Users/wangjuntao/github/pgdata:/var/lib/postgresql/data"

